version: "3.8"
services:
  backend:
    build:
      context: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    env_file:
      - ./.env
    image: application-django:image
    container_name: application-django-container
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
